apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappdeploy
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demoappimage
          image: navin009/demoapp:v1
          ports:
              - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: demo
