name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.0
    - run: npm ci
    - run: npm run build --if-present
    - name: Installing npm packages
      run: npm install check
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: demoappContainerRegistery
        # Container registry password
        password: B4DsZte0Hbuy2M5=eR2=fTmn+0bb81l7 
        # Container registry server url
        login-server: demoappcontainerregistery.azurecr.io
        
        
    - name: Docker build and push
      run: |
        docker build . -t demoappcontainerregistery.azurecr.io/navindemo:latest
        docker push demoappcontainerregistery.azurecr.io/navindemo:latest
